# Site settings
author: Chris Tompkins 
title: Chris Tompkins <> Web Development Journey
header-img: img/home-bg.png
email: chtompkins026@gmail.com
copyright_name: Chris Tompkins 
description: > # this means to ignore newlines until "baseurl:"
  many hills and turns, but I am still going 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  chtompkins026

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
